vars:
  - ws: 'C:/Users/tfo46/e_Python/a_rbm/rapid-gwm-build/examples/pakipaki/dvc_stuff'  # path to

stages:
  setup-build:
    cmd: python -m debugpy --listen 5678 --wait-for-client  ${ws}/scripts/setup_build.py --config pakipaki_v0.yaml --out_dir output --graph_name output_graph0.txt
    deps:
      - dvc_stuff/scripts/setup_build.py
      - pakipaki_v0.yaml
    outs:
      - output
